package whatsapp
package whatsapp

import (







































































}	}		t.Errorf("Expected raw message %q, got %q", rawMessage, intent.RawMessage)	if intent.RawMessage != rawMessage {	intent := ParseIntent("+221771234567", rawMessage)	rawMessage := "solde please"func TestParseIntentPreservesRaw(t *testing.T) {}	}		t.Errorf("Expected phone %s, got %s", phoneNumber, intent.PhoneNumber)	if intent.PhoneNumber != phoneNumber {	intent := ParseIntent(phoneNumber, "SOLDE")	phoneNumber := "+221771234567"func TestParseIntentPhoneNumber(t *testing.T) {}	}		}			t.Errorf("detectCommand(%q): expected %v, got %v", test.input, test.expected, result)		if result != test.expected {		result := detectCommand(test.input)	for _, test := range tests {	}		{"RANDOM", IntentUnknown},		{"INFO", IntentInfo},		{"AIDE", IntentHelp},		{"CYCLE", IntentCycle},		{"HISTO", IntentHistory},		{"BALANCE", IntentBalance},		{"SOLDES", IntentBalance},		{"SOLDE", IntentBalance},	}{		expected Intent		input    string	tests := []struct {func TestDetectCommand(t *testing.T) {}	}		})			}				t.Errorf("Expected %v, got %v for input %q", test.expected, intent.Command, test.input)			if intent.Command != test.expected {			intent := ParseIntent("+221771234567", test.input)		t.Run(test.name, func(t *testing.T) {	for _, test := range tests {	}		{"solde extra words", IntentBalance, "solde with extra text"},		{"", IntentUnknown, "empty string"},		{"UNKNOWN", IntentUnknown, "unknown command"},		{"INFO", IntentInfo, "INFO"},		{"AIDE", IntentHelp, "AIDE"},		{"CYCLE", IntentCycle, "CYCLE"},		{"HISTO", IntentHistory, "HISTO"},		{"  solde  ", IntentBalance, "solde with spaces"},		{"solde", IntentBalance, "lowercase solde"},		{"SOLDE", IntentBalance, "uppercase SOLDE"},	}{		name     string		expected Intent		input    string	tests := []struct {func TestParseIntent(t *testing.T) {)	"testing"