package whatsapp

























































































































}	Progress  string	EndDate   string	StartDate string	Status    string	Name      string	ID        stringtype CycleInfo struct {// CycleInfo represents current cycle}	Description string	Amount      string	To          string	From        string	Timestamp   stringtype Transaction struct {// Transaction represents ledger entry}	NextCollectionDate string	ActiveCycle   string	Balance       string	MembersCount  int	Name          string	ID            stringtype GroupInfo struct {// Group represents a tontine group}	RecipientID string `json:"recipient_id"`	Timestamp string `json:"timestamp"`	Status    string `json:"status"`	ID        string `json:"id"`type Status struct {}	Body string `json:"body"`type Text struct {}	Type      string `json:"type"`	Text      Text   `json:"text"`	Timestamp string `json:"timestamp"`	From      string `json:"from"`	ID        string `json:"id"`type Message struct {}	Name string `json:"name"`type Profile struct {}	WaID    string  `json:"wa_id"`	Profile Profile `json:"profile"`type Contact struct {}	PhoneNumberID      string `json:"phone_number_id"`	DisplayPhoneNumber string `json:"display_phone_number"`type Metadata struct {}	Statuses         []Status     `json:"statuses"`	Messages         []Message    `json:"messages"`	Contacts         []Contact    `json:"contacts"`	Metadata         Metadata     `json:"metadata"`	MessagingProduct string       `json:"messaging_product"`type WebhookValue struct {}	Field string       `json:"field"`	Value WebhookValue `json:"value"`type Changes struct {}	Changes   []Changes `json:"changes"`	Timestamp int64     `json:"timestamp"`	ID        string    `json:"id"`type Entry struct {}	Entry  []Entry `json:"entry"`	Object string  `json:"object"`type WebhookRequest struct {// WhatsApp Webhook structures}	Text string `json:"text"`	To   string `json:"to"`type WhatsAppMessage struct {// WhatsAppMessage is sent back to Meta API}	FormattedText   string // Pre-formatted response (for direct use)	Error           string	Data            interface{} // Could be balance, transactions, cycle info, etc.	Success         bool	CommandExecuted stringtype BotResponse struct {// BotResponse represents bot's internal response}	RawMessage  string	Command     Intent	PhoneNumber stringtype UserIntent struct {// UserIntent represents parsed user intent)	IntentUnknown    Intent = "UNKNOWN"	IntentInfo       Intent = "INFO"	IntentHelp       Intent = "AIDE"	IntentCycle      Intent = "CYCLE"	IntentHistory    Intent = "HISTO"	IntentBalance    Intent = "SOLDE"const (type Intent string// Intent types